# Generated by Django 6.0.3 on 2026-03-17 11:15

import Fishing_shop.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fishing_shop', '0002_categories_alter_manufacturer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to=settings.AUTH_USER_MODEL, verbose_name='пользоваетель')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item_in_bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[Fishing_shop.models.validator_for_bucket], verbose_name='Количество')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Fishing_shop.bucket', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_items', to='Fishing_shop.product', verbose_name='Товар')),
            ],
        ),
    ]
